apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-init
  namespace: app-sandbox
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: initiator
          image: mongo:5.0
          command: ["bash", "-c"]
          args:
            - |
              sleep 20;
              echo "Initiating replica set...";
              mongo --host mongodb-0.mongodb.app-sandbox.svc.cluster.local:27017 <<EOF
              rs.initiate({
                _id: "rs0",
                members: [
                  { _id: 0, host: "mongodb-0.mongodb.app-sandbox.svc.cluster.local:27017" },
                  { _id: 1, host: "mongodb-1.mongodb.app-sandbox.svc.cluster.local:27017" },
                  { _id: 2, host: "mongodb-2.mongodb.app-sandbox.svc.cluster.local:27017" }
                ]
              });
              EOF
